// <auto-generated />
using System;
using Inventory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20190527064615_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Inventory.Models.Goods", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BuyDate");

                    b.Property<string>("BuyerName");

                    b.Property<int>("Count");

                    b.Property<string>("GiftedFrom");

                    b.Property<int?>("HouseId");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long>("Price");

                    b.Property<int>("ReciveType");

                    b.Property<int?>("RegisterNumber");

                    b.Property<int?>("StoreId");

                    b.HasKey("ID");

                    b.HasIndex("HouseId");

                    b.HasIndex("StoreId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Inventory.Models.House", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("Area");

                    b.Property<string>("DocumentSituation");

                    b.Property<string>("EarthSituation");

                    b.Property<string>("HeadName");

                    b.Property<int>("HouseSituation");

                    b.Property<int>("HouseType");

                    b.HasKey("ID");

                    b.ToTable("House");
                });

            modelBuilder.Entity("Inventory.Models.Store", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Inventory.Models.Goods", b =>
                {
                    b.HasOne("Inventory.Models.House", "House")
                        .WithMany("Goodses")
                        .HasForeignKey("HouseId");

                    b.HasOne("Inventory.Models.Store", "Store")
                        .WithMany("Goodses")
                        .HasForeignKey("StoreId");
                });
#pragma warning restore 612, 618
        }
    }
}
